Add Coaliron Press URDF
OSU-AIMS/coaliron_16ton_support pull request #14
Opened 2023-01-13 18:38 UTC by Tal-Yankevich

Wrote urdf for the coaliron press
Added links to attach top/bottom tool tips, and world frame to orient the base of the press.

2023-01-19 20:02 UTC, Tal-Yankevich commented on urdf/16ton_macro_v2.xacro
> +    </link>
I split the collision mesh into a convex hull of the bottom trapezoid, and the decimated top part with boxes over certain spots

2023-01-19 20:04 UTC, Tal-Yankevich commented on urdf/16ton_macro_v2.xacro
> +    </joint>
I slightly adjusted the stroke length, on the real press it's about 11.25in.

2023-01-19 20:14 UTC, Tal-Yankevich commented on urdf/16ton_macro_v2.xacro
> +        <limit lower="0" upper="0.2921" effort="100" velocity="10"/>
Because the location of press_link was moved to the upper_mount location, the overlapping reference frames were redundant. press_link was removed, and upper_mount is now the moving link, starting below the press_frame.

2023-01-24 17:55 UTC, acbuynak requested changes
This looks great! I like the `tf` frame layout and think it's just about ready to merge.

Just one small change, looking at difference between the collision and visual meshes on the moveable upper mount... it appears they are slightly offset along the X-axis. Hard to tell from the photo below, but fairly noticeable when switching back and forth between Visual and Collision meshes in RViz.

![image](https://user-images.githubusercontent.com/44533530/214370387-c7092a37-fada-42b9-a0ce-a0084e200821.png)

2023-02-02 17:12 UTC, acbuynak approved these changes
Ready to merge

2023-02-02 17:12 UTC, merged